### ISSUE TITLE
Invalid syntax issue

### ISSUE THREAD

**Issue by nikhila05** [gusutabopb/imongo#2]
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/imongo/__main__.py", line 2, in <module>
    from .kernel import MongoKernel
  File "/usr/local/lib/python3.5/dist-packages/imongo/kernel.py", line 165
    spawn_cmd = ['mongo', f'--eval "{prompt_cmd}; {dir_func}"']
                                                             ^
SyntaxError: invalid syntax

**Comment by gusutabopb** [comment]
Could you please elaborate a bit more?

**Comment by semarf** [comment]
I have the same issue, on Ubuntu 16.04, cannot start the kernel , this loops in the logs:

`[I 19:03:57.050 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 5895ffb2-24cb-4a4e-ab4d-b66d28032354 restarted
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/imongo/__main__.py", line 2, in <module>
    from .kernel import MongoKernel
  File "/usr/local/lib/python3.5/dist-packages/imongo/kernel.py", line 165
    spawn_cmd = ['mongo', f'--eval "{prompt_cmd}; {dir_func}"']
                                                             ^
SyntaxError: invalid syntax
`

**Comment by gusutabopb** [comment]
IMongo only support Python 3.6+. Both @semarf and @nikhila05 seem to be using Python 3.5, which doesn't support [f-strings](https://www.python.org/dev/peps/pep-0498/). I will update the docs to make sure this is more explicit. In the meantime, please let me know if you have any problems with Python 3.6.
