### ISSUE TITLE
Add Jupyter Lab support

### ISSUE THREAD

**Issue by gusutabopb** [gusutabopb/imongo#5]
IMongo currently doesn't work properly on Jupyter Lab.

Currently, the kernel show up on Jupyter Lab interface and starts, but nothing is displayed when executing Mongo shell commands.

Also, it seems a Jupyter Lab extension would be necessary to make the collapsable pretty printing viewing functionality (currently implemented through third-party JS library) available.

**Comment by boun** [comment]
Hi,

there is no need for an extension. JupyterLab comes with a json extension. 

<img width="993" alt="Screenshot 2019-03-31 at 21 30 58" src="https://user-images.githubusercontent.com/3662452/55293939-60a80980-53fc-11e9-8c45-adb0ac346186.png">

After some poking around, it was pretty straight forward to do. However I don't know how to detect if running in jupyterlab or classic. And some serious lazyness. Hence no pull request, find the changes (this time against your upstream ;) in my fork: https://github.com/boun/imongo

**Comment by diegodorgam** [comment]
Any progress on this?

**Comment by rodfersou** [comment]
@boun getting error when try to install here your version:

```python
    Installing Jupyter kernelspec
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xze0ax_l/imongo-kernel_90f3e8dc7ce647338d278e703e02556c/setup.py", line 37, in <module>
        setup(name='imongo-kernel',
      File "/srv/rodfersou/coding_interview/.direnv/shared/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-xze0ax_l/imongo-kernel_90f3e8dc7ce647338d278e703e02556c/setup.py", line 19, in run
        from jupyter_client.kernelspec import KernelSpecManager
    ModuleNotFoundError: No module named 'jupyter_client'
```

**Comment by boun** [comment]
@rodfersou `pip install jupyter_client` should do the trick. That should have come with jupyter though...
